### ISSUE TITLE
Cannot edit body parameters 

### ISSUE THREAD

**Issue by poisenbery** [hinablue/ComfyUI_3dPoseEditor#12]
It should be possible to edit the body parameters, but the section only appears for a moment before vanishing. 

[Screencast from 03-31-2024 09:44:49 AM.webm](https://github.com/hinablue/ComfyUI_3dPoseEditor/assets/78466408/728228fc-04fa-46fa-9346-05a14a959c90)

**Comment by DarkTwilight** [comment]
This is still happening, and on a new install of ComfyUI, it is not fixed

**Comment by Duemellon** [comment]
I am having this problem as well.
