### ISSUE TITLE
PermissionError:

### ISSUE THREAD

**Issue by xueqing0622** [hinablue/ComfyUI_3dPoseEditor#2]
PermissionError: [WinError 5] 拒绝访问。: 'F:\\ComfyUI\\ComfyUI\\web\\extensions\\ComfyUI_3dPoseEditor\\.git\\objects\\pack\\pack-cc22a12026bbde61fc3c2c76800cbdb93447e0aa.idx'

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor module for custom nodes: [WinError 5] 拒绝访问。: 'F:\\ComfyUI\\ComfyUI\\web\\extensions\\ComfyUI_3dPoseEditor\\.git\\objects\\pack\\pack-cc22a12026bbde61fc3c2c76800cbdb93447e0aa.idx'
Comfyroll Custom Nodes: Loaded

**Comment by hinablue** [comment]
Cause package include workbox, I removed.
