### ISSUE TITLE
[Errno 2] No such file or directory:'D:\\ComfyUI\\temp\\3dposeeditor\\OpenPoseEditor_0_pose.png'

### ISSUE THREAD

**Issue by yelloowdoor** [hinablue/ComfyUI_3dPoseEditor#22]
I install the node by ComfyUI Manager, and the node shows up successfully.
But after I clicked queue prompt, this error occurred.
I checked the folder, no png in it.
Is there any way to fix it? I've reinstall it several times.

Error occurred when executing Hina.PoseEditor3D:

[Errno 2] No such file or directory: 'D:\\ComfyUI\\temp\\3dposeeditor\\OpenPoseEditor_0_pose.png'

File "d:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "d:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "d:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor\poseEditor3D_node.py", line 54, in output_pose
i = Image.open(image_path)
File "C:\Users\user\miniconda3\envs\ComfyUI\lib\site-packages\PIL\Image.py", line 3236, in open
fp = builtins.open(filename, "rb")

**Comment by Engineer-D** [comment]
You have to create your own png files and place them in your temp/3dposeeditor folder.

create the pose with the 3d pose editor, click on the triangle in the preview menu (below the lock) then tap each of the images displayed, each one will represent normal, pose, canny depth. save them into your temp folder and you are good to go

**Comment by Zak525** [comment]
I encountered the same issue, and I found that the main reason was that when I used the embedded 3D POSE EDITOR in the node, clicking "Generate" did not produce the corresponding PNG images. Therefore, if the node is imported and already contains the names of four images, it is feasible to follow [Engineer-D](https://github.com/Engineer-D)
![3dposeeditor](https://github.com/user-attachments/assets/1e1e5ef3-ddca-46d0-8362-aecc4237de56)
's suggestion: first, generate these four images in the web version of the 3D POSE EDITOR and then place them in the temp/3dposeeditor folder. However, if I create the node myself, the names of these four images will be "undefined," and when the embedded editor's generation function is unavailable, I have no way to proceed.

**Comment by Zak525** [comment]
I turn on chrom F12 console, find this error:
Error loading extension /extensions/ComfyUI_3dPoseEditor/js/main.js Error: Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gn.createRoot (main.js:40:55756)
    at LV (main.js:3441:30649)
    at main.js:3441:30767

**Comment by yelloowdoor** [comment]
I finally run the workflow successfully. Here are some tips for who encounters the same issue.
- If you can't see the 3D pose editor screen in the node as below, try to run ComfyUI in Edge instead of Chrome.
![image](https://github.com/user-attachments/assets/1c04e2cd-e0bb-4cde-a0f4-0435cfbd9b5d)
- If there is an error like mine, go to Web 3D pose editor to download four necessary images on the corner. (Click the triangle button to generate them)
![image](https://github.com/user-attachments/assets/2e3c7899-9b60-4906-bcae-f049c985439f)
- Named the images as below and put them in \ComfyUI\temp\3dposeeditor
![image](https://github.com/user-attachments/assets/e5927291-3fc4-4d0d-87a5-6cff988ebd16)
- Supposed to be okay in Edge browser.
![image](https://github.com/user-attachments/assets/a760d742-0f42-4217-956f-2f230171ce47)

Thank you so much for help! I really appreciate @Engineer-D & @Zak525 's support.
