### ISSUE TITLE
0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor

### ISSUE THREAD

**Issue by wibur0620** [hinablue/ComfyUI_3dPoseEditor#4]

**Comment by wibur0620** [comment]
** ComfyUI startup time: 2023-12-29 19:22:07.623925
** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI\venv\Scripts\python.exe
** Log path: D:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 65268 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.54.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Manager (V1.17.1)[Impact Pack] Wildcards loading done.

### ComfyUI Revision: 1863 [12e822c6] | Released on '2023-12-28'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
--------------
Mixlab Nodes: Loaded
--------------
Total VRAM 8188 MB, total RAM 65268 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.1+cu121
Traceback (most recent call last):
  File "D:\AI\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor\__init__.py", line 49, in <module>
    update_web()
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor\__init__.py", line 25, in update_web
    shutil.rmtree(extensions_folder)
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 600, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 597, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\AI\\ComfyUI\\web\\extensions\\ComfyUI_3dPoseEditor'

Cannot import D:\AI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor module for custom nodes: [WinError 3] 系统找不到指定的路径。: 'D:\\AI\\ComfyUI\\web\\extensions\\ComfyUI_3dPoseEditor'
------------------------------------------------
Comfyroll Custom Nodes v1.54 :  162 Nodes Loaded
------------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Node -> ExtrasNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
Node -> TranslateNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Davemane42 Custom Nodes: Loaded
FizzleDorf Custom Nodes: Loaded
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!

[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\AI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 199 nodes successfully.

        "Every great dream begins with a dreamer." - Harriet Tubman


Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.2 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.2 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.5 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   0.7 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.7 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.3 seconds: D:\AI\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.5 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

https_key OK:  D:\AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt D:\AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key
Starting server

To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
FETCH DATA from: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
data_path:  D:\AI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by cqwcqwcqwa** [comment]
the same

**Comment by hinablue** [comment]
I rewrite all the load method, now it work fine.
